### ISSUE TITLE
active samplers with a different type refer to the same texture image unit

### ISSUE THREAD

**Issue by hamoid** [kosowski/SimplePBR#4]
Hi Nacho :)

I was trying to understand the error with Intel graphics on Linux. It's this:
```
OpenGL error 1280 at top endDraw(): invalid enumerant
RuntimeException: Cannot validate shader program:
active samplers with a different type refer to the same texture image unit
```

If this is a valid error, it means that the same texture is accessed twice with different samplers.

The only place samplers are used is in this file:
https://github.com/kosowski/SimplePBR/blob/master/data/shaders/pbr/simplepbr.frag

The only two types of samplers are 4 x `sampler2D` and 1 x `samplerCube`.

```
uniform samplerCube envd;  // prefiltered env cubemap
uniform sampler2D roughnessMap;    // roughness texture
uniform sampler2D metalnessMap;    // metalness texture.
uniform sampler2D iblbrdf; // IBL BRDF normalization precalculated tex
uniform sampler2D albedoTex;     // base texture (albedo)
```

If the error is right (it could be a bug in Processing) it means that `envd` is the same texture as in one of the other 4 textures. I tried to verify this and `envd` is assigned in this line:
https://github.com/kosowski/SimplePBR/blob/master/src/estudiolumen/simplepbr/SimplePBR.java#L45
with the value `5`. That value being hardcoded makes it hard to know which other texture might occupy that slot. My thought is: if a texture is really used twice, would it be enough to `.copy()` that texture in Processing so it's not reused?

**Comment by kosowski** [comment]
Hi aBe!

Thanks for looking into it. Having the texture unit hardcoded is surely a bad idea, but when I looked into Processing code couldn't find a way to access unassigned texture units. I can't remember well, but the methods dealing with texture unit assignation were not publicly exposed. So I just set a texture unit with a high id. Any idea on how to deal with this would be great :)

I already tried using just a samplerCube and one sampler2D (loaded and set just once), and different texture units for the samplerCube, but I always get the same error (win10 and intel gfx) "Validation Error: Samplers of different types point to the same texture unit", as in this Processing issue https://github.com/processing/processing/issues/5507 so, it might be related..

**Comment by kosowski** [comment]
I think this is solved with the newest release (v0.3). The mentioned Processing bug refers to samplerCubes, so I removed it and switched to equirectangular enviroment maps in case the shader fails to compile. Also, changing texture2D() to texture().

This way, the library is working on the Intel integrated graphics cards and OSX machines I have tested. Could you please confirm on Linux?

**Comment by hamoid** [comment]
Great news :)

I downloaded 0.3 and placed it into the libraries folder but somehow the library is not detected. The examples are not shown in the examples menu, and if I load an example the SimplePBR classes are not found for some reason.

I see this in the console when loading the file:

```
removing /home/funpro/Desktop/edu/src/processing/libraries/SimplePBR/examples/HelloPBR/HelloPBR.pde
java.lang.Exception
	at processing.app.ui.Recent.remove(Recent.java:246)
	at processing.app.ui.Recent.append(Recent.java:294)
	at processing.app.Base.handleOpen(Base.java:1367)
	at processing.app.Base.handleOpen(Base.java:1314)
	at processing.app.Base.handleOpen(Base.java:1303)
	at processing.app.ui.Recent$1.actionPerformed(Recent.java:217)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Any ideas?

**Comment by hamoid** [comment]
Works for me! Looks great :)
```
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.1.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 20.1.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by kosowski** [comment]
Thanks aBe! Closing the issue then 🎉
